# Generated by Django 2.2 on 2021-06-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0002_auto_20210614_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
