# Generated by Django 2.2 on 2021-06-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0004_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.URLField(),
        ),
    ]
